version: '3.1'
services:
  kong:
    image: kong:0.14.1
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres_postgres
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: password
      KONG_PG_DATABASE: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - swarm
networks:
  swarm:
    external: true
